INSERT INTO Category VALUES 
(NULL, "Flags"), 
(NULL, "Medals"),
(NULL, "Ribbons"),
(NULL, "Badges"),
(NULL, "Pins"),
(NULL, "Stationery"),
(NULL, "Toys"),
(NULL, "Miscellaneous");

INSERT INTO Product(ProductID, CategoryID, Description, Price) VALUES 
(NULL, 1, 'London 2012 Official Olympic Flag', '20'), 
(NULL, 1, 'Opening Ceremony Flag London 2012', '15'), 
(NULL, 1, 'Closing Ceremony Flag London 2012', '15'), 
(NULL, 2, 'London 2012 Olympic Games Sports Collection Ð Boccia', '3'), 
(NULL, 2, 'London 2012 Olympic Games Sports Collection Ð Weightlifting', '3'), 
(NULL, 2, 'London 2012 Olympics Sports Collection Ð Football', '3'), 
(NULL, 2, 'London 2012 Olympic Games Sports Collection Ð Fencing', '3'), 
(NULL, 3, 'Olympic Red Ribbon', '2.9'), 
(NULL, 3, 'Olympic Union Jack Ribbon', '2.99'), 
(NULL, 4, 'London 2012 Olympic Games Union Jack logo medium pin badge', '5'), 
(NULL, 4, 'London 2012 Union Jack Paralympic pin badge', '5'), 
(NULL, 4, 'London 2012 official Paralympic logo pin badge', '5'), 
(NULL, 4, 'London 2012 Olympics Football duo pictogram set', '10'), 
(NULL, 4, 'London 2012 Pictogram Artistic Gymnastic - New Gold', '5'), 
(NULL, 4, 'London 2012 national flag Italy pin badge', '5'), 
(NULL, 4, 'London 2012 Olympic Games Mandeville walking to school', '7'), 
(NULL, 4, 'London 2012 Olympics national flag Spain pin badge', '5'), 
(NULL, 4, 'London 2012 pictogram Football - New Gold', '5'), 
(NULL, 4, 'London 2012 pictogram Swimming - New Gold', '5'), 
(NULL, 4, 'London 2012 pictogram Track Cycling - New Gold', '5'), 
(NULL, 5, 'Games Logo Ð Pink', '4'), 
(NULL, 5, 'Games Logo Ð Orange', '4'), 
(NULL, 5, 'Games Logo Ð Blue', '4'), 
(NULL, 5, 'Games Logo Ð Green', '4'), 
(NULL, 5, 'Games Logo Ð Paralympic Games', '4'), 
(NULL, 5, 'Games Logo Ð White', '4'), 
(NULL, 5, 'Countdown Ð 4 Years To Go', '5'), 
(NULL, 5, 'Handover Ð The Handover Ceremony', '5'), 
(NULL, 5, 'Handover Ð London Ð Beijing Ð London Bus', '5'), 
(NULL, 5, 'Games Logo - Union Flag', '5'), 
(NULL, 5, 'Handover - VIP Pin Ð Beijing/London', '5'), 
(NULL, 5, 'Handover - Paralympic Bus', '5'), 
(NULL, 5, 'Heroes Parade - Team GB', '5'), 
(NULL, 5, 'Heroes Parade - Paralympics GB', '5'), 
(NULL, 5, 'London at Night - Old Royal Naval College', '5'), 
(NULL, 5, 'London at Night - Tower Bridge', '5'), 
(NULL, 5, 'London at Night - St Pauls Cathedral', '5'), 
(NULL, 5, 'London at Night - Big Ben', '5'), 
(NULL, 5, 'London at Night - Houses of Parliament', '5'), 
(NULL, 5, 'London at Night - Westminster Abbey', '5'), 
(NULL, 5, 'London at Night - Buckingham Palace', '5'), 
(NULL, 5, 'London at Night - Marble Arch', '5'), 
(NULL, 5, 'London at Night - Albert Memorial', '5'), 
(NULL, 5, 'London at Night - Kensington Palace', '5'), 
(NULL, 5, 'Markets Ð Borough', '5'), 
(NULL, 5, 'Markets Ð Greenwich', '5'), 
(NULL, 5, 'Markets - Portobello Road', '5'), 
(NULL, 5, 'Markets - Columbia Road', '5'), 
(NULL, 5, 'Markets Ð Camden', '5'), 
(NULL, 5, 'Markets - Brick Lane', '5'), 
(NULL, 5, 'Music - Concert Stage', '5'), 
(NULL, 5, 'Music Ð Drums', '5'), 
(NULL, 5, 'Music Ð Guitar', '5'), 
(NULL, 5, 'Music Ð Tent', '5'), 
(NULL, 5, 'Music Ð Speakers', '5'), 
(NULL, 5, 'Music Ð DJ', '5'), 
(NULL, 5, 'Music Ð Dancers', '5'), 
(NULL, 5, 'Christmas Ð Tree', '5'), 
(NULL, 5, 'Christmas Ð Snowflake', '5'), 
(NULL, 5, 'Christmas Ð Snowman', '5'), 
(NULL, 5, 'Christmas Ð Present', '5'), 
(NULL, 5, 'Christmas Ð Wreath', '5'), 
(NULL, 5, 'Guards Ð Policeman', '5'), 
(NULL, 5, 'Guards Ð Policewoman', '5'), 
(NULL, 5, 'Guards - Yeoman Warder (Undress Uniform)', '5'), 
(NULL, 5, 'Guards - Yeoman of the Guard (State Dress Uniform)', '5'), 
(NULL, 5, 'Guards - Guard on Sentry Duty', '5'), 
(NULL, 5, 'Guards - Household Cavalry Ð Mounted', '5'), 
(NULL, 5, 'Guards - Household Cavalry Ð Standing', '5'), 
(NULL, 5, 'Landmarks - Big Ben', '5'), 
(NULL, 5, 'Landmarks - Chinatown Gates', '5'), 
(NULL, 5, 'Landmarks - Tower Bridge', '5'), 
(NULL, 5, 'Landmarks - City Hall', '5'), 
(NULL, 5, 'Landmarks Ð Monument', '5'), 
(NULL, 5, 'Landmarks - Houses of Parliament', '5'), 
(NULL, 5, 'Landmarks - Albert Memorial', '5'), 
(NULL, 5, 'Landmarks - Buckingham Palace', '5'), 
(NULL, 5, 'Weather - Heavy Showers', '5'), 
(NULL, 5, 'Weather - Light Showers', '5'), 
(NULL, 5, 'Weather - Wind and Storm', '5'), 
(NULL, 5, 'Weather Ð Raining', '5'), 
(NULL, 5, 'Weather Ð Lightning', '5'), 
(NULL, 5, 'Weather Ð Snowing', '5'), 
(NULL, 5, 'Weather Ð Sunny', '5'), 
(NULL, 5, 'Soldier', '5'), 
(NULL, 5, 'Punk Ð Green', '5'), 
(NULL, 5, 'Punk Ð Pink', '5'), 
(NULL, 5, 'Flowers (Spring) Ð Bluebell', '5'), 
(NULL, 5, 'Flowers (Spring) Ð Cowslip', '5'), 
(NULL, 5, 'Flowers (Spring) Ð Daffodil', '5'), 
(NULL, 5, 'Flowers (Spring) Ð Violet', '5'), 
(NULL, 5, 'Flowers (Summer) Ð Buttercup', '5'), 
(NULL, 5, 'Flowers (Summer) Ð Cornflower', '5'), 
(NULL, 5, 'Flowers (Summer) Ð Daisy', '5'), 
(NULL, 5, 'Flowers (Summer) Ð Foxglove', '5'), 
(NULL, 5, 'Flowers (Autumn) - Dog Rose', '5'), 
(NULL, 5, 'Flowers (Autumn) - Field Scabious', '5'), 
(NULL, 5, 'Flowers (Autumn) Ð Hollyhock', '5'), 
(NULL, 5, 'Flowers (Autumn) - Sweet Alison/Alyssum', '5'), 
(NULL, 5, 'Flowers (Winter) - Christmas Rose', '5'), 
(NULL, 5, 'Flowers (Winter) Ð Crocus', '5'), 
(NULL, 5, 'Flowers (Winter) Ð Eranthis', '5'), 
(NULL, 5, 'Flowers (Winter) Ð Snowdrops', '5'), 
(NULL, 5, 'Teapot - Cauliflower Teapot', '5'), 
(NULL, 5, 'Teapot - Blue Italian Teapot', '5'), 
(NULL, 5, 'Teapot - Ornate Black Teapot', '5'), 
(NULL, 5, 'Teapot - Greek Dancers Teapot', '5'), 
(NULL, 5, 'Teapot - Leafy Teapot', '5'), 
(NULL, 5, 'Teapot - Victorian Yellow Teapot', '5'), 
(NULL, 5, 'Teapot - Art Deco Teapot', '5'), 
(NULL, 5, 'Teapot - Pink Teapot', '5'), 
(NULL, 5, 'Afternoon Tea - Cake Stand', '5'), 
(NULL, 6, 'London 2012 Olympic Museum pre-1948 postcard pack of 5', '3'), 
(NULL, 6, 'London 2012 Wenlock and Mandeville 10pc stationery ', '10'), 
(NULL, 6, 'London 2012 Olympic Games Union Jack Neoprene 15in laptop sleeve', '20'), 
(NULL, 6, 'London 2012 Wenlock and Mandeville postcards pack of five', '3'), 
(NULL, 6, 'London 2012 Olympics Union Jack Wenlock 8 colour pen', '5'), 
(NULL, 6, 'London 2012 Union Jack neoprene 13in laptop sleeve', '18'), 
(NULL, 6, 'Filofax personal London 2012 line burst pink', '37'), 
(NULL, 6, 'Filofax personal London 2012 Union flag chocolate', '90'), 
(NULL, 6, 'London 2012 Paralympics Mandeville 8 colour pen', '5'), 
(NULL, 7, 'Team GB Olympic Pride the Lion soft toy Ð 20cm', '5'), 
(NULL, 7, 'London 2012 Olympic Games Wenlock mascot soft toy Ð 20cm', '5'), 
(NULL, 7, 'London 2012 Paralympic Games mascot Mandeville soft toy 30cm', '10'), 
(NULL, 7, 'London 2012 Olympic Games mascot Wenlock soft toy 30cm', '10'), 
(NULL, 7, 'London 2012 Olympics Wenlock and Mandeville soft toys 30cm', '19'), 
(NULL, 7, 'London 2012 Olympic Games Union Jack Wenlock soft toy 25cm', '5'), 
(NULL, 8, 'adidas London 2012 sporting Wenlock girls t-shirt', '12'), 
(NULL, 8, 'adidas London 2012 sporting Wenlock boys t-shirt', '12'), 
(NULL, 8, 'London 2012 Tableau figure', '1250'), 
(NULL, 8, 'London 2012 Olympian figure', '150'), 
(NULL, 8, 'London 2012 Olympiad plaque', '350'), 
(NULL, 8, 'Little London 2012 Olympics - 5 handmade glass decorations', '45'), 
(NULL, 8, 'London Three Times Host City Tri-Metal Set', '297'); 
