DROP TABLE Cart_Product;
DROP TABLE Purchase;
DROP TABLE Cart;
DROP TABLE Customer;
DROP TABLE Product;
DROP TABLE Category;

CREATE TABLE Category (
	CategoryID INT NOT NULL AUTO_INCREMENT,
	CategoryName VARCHAR(40) NOT NULL,
	PRIMARY KEY (CategoryID)
) ENGINE=INNODB;

CREATE TABLE Product (
	ProductID INT NOT NULL AUTO_INCREMENT,
	CategoryID INT NOT NULL,
	Description VARCHAR(100) NOT NULL,
	Price DECIMAL(10, 2) NOT NULL,
	Quantity INT NULL,
	PRIMARY KEY (ProductID),
	INDEX (CategoryID),
	FOREIGN KEY (CategoryID) REFERENCES Category(CategoryID)
) ENGINE=INNODB;

CREATE TABLE Cart (
	CartID INT NOT NULL AUTO_INCREMENT,
	TotalPrice DECIMAL(10, 2) NOT NULL,
	DateCreated DATETIME,
	PRIMARY KEY (CartID)
) ENGINE=INNODB;

CREATE TABLE Cart_Product (
	CartID INT NOT NULL,
	ProductID INT NOT NULL,
	Quantity INT NOT NULL,
	PRIMARY KEY (CartID, ProductID),
	INDEX (CartID),
	INDEX (ProductID),
	FOREIGN KEY (CartID) REFERENCES Cart(CartID),
	FOREIGN KEY (ProductID) REFERENCES Product(ProductID)
) ENGINE=INNODB;

CREATE TABLE Customer (
	CustomerID INT NOT NULL AUTO_INCREMENT,
	Title VARCHAR(5) NOT NULL,
	GivenName VARCHAR(40) NOT NULL,
	Surname VARCHAR(40) NOT NULL,
	Email VARCHAR(40) NOT NULL,
	Address VARCHAR(40) NOT NULL,
	Country VARCHAR(40) NOT NULL,
	State VARCHAR(40) NOT NULL,
	Postcode VARCHAR(40) NOT NULL,
	CreditNo VARCHAR(40) NOT NULL,
	PRIMARY KEY (CustomerID)
) ENGINE=INNODB;

CREATE TABLE Purchase (
	PurchaseID INT NOT NULL AUTO_INCREMENT,
	CustomerID INT NOT NULL,
	CartID INT NOT NULL,
	Status VARCHAR(40) NOT NULL,
	PRIMARY KEY (PurchaseID),
	INDEX (CustomerID),
	INDEX (CartID),
	FOREIGN KEY (CustomerID) REFERENCES Customer(CustomerID),
	FOREIGN KEY (CartID) REFERENCES Cart(CartID)
) ENGINE=INNODB;